routes/frontend.php
<?php

use App\Http\Controllers\Frontend\Company\Auth\CompanyForgotPasswordController;
use App\Http\Controllers\Frontend\Company\Auth\CompanyLoginController;
use App\Http\Controllers\Frontend\Company\Auth\CompanyRegisterController;
use App\Http\Controllers\Frontend\Company\Auth\CompanyResetPasswordController;
use App\Http\Controllers\Frontend\Company\CompanyHomeController;
use App\Http\Controllers\Frontend\JobSeeker\Auth\JobSeekerForgotPasswordController;
use App\Http\Controllers\Frontend\JobSeeker\Auth\JobSeekerLoginController;
use App\Http\Controllers\Frontend\JobSeeker\Auth\JobSeekerRegisterController;
use App\Http\Controllers\Frontend\JobSeeker\Auth\JobSeekerResetPasswordController;
use App\Http\Controllers\Frontend\JobSeeker\JobSeekerEducationController;
use App\Http\Controllers\Frontend\JobSeeker\JobSeekerExperienceController;
use App\Http\Controllers\Frontend\JobSeeker\JobSeekerHomeController;
use App\Http\Controllers\Frontend\JobSeeker\JobSeekerProfileController;
use App\Http\Controllers\Frontend\JobSeeker\JobSeekerResumeController;
use Illuminate\Support\Facades\Route;

    Route::get('/', function () {
        return view('frontend.index');
    })->name('index');

    Route::prefix('jobseeker')->name('jobseeker.')->group(function() {
        Route::get('register', [JobSeekerRegisterController::class, 'viewRegister'])->name('register.view');
        Route::post('register', [JobSeekerRegisterController::class, 'register'])->name('register');
        
        Route::get('login', [JobSeekerLoginController::class, 'viewlogin'])->name('login.view');
        Route::post('login', [JobSeekerLoginController::class, 'login'])->name('login');

        Route::post('logout', [JobSeekerLoginController::class, 'logout'])->name('logout');

        Route::post('password/email', [JobSeekerForgotPasswordController::class, 'sendResetLinkEmail'])->name('password.email');
        Route::get('password/reset', [JobSeekerForgotPasswordController::class, 'showLinkRequestForm'])->name('password.request');

        Route::post('password/reset', [JobSeekerResetPasswordController::class, 'reset']);
        Route::get('password/reset/{token}', [JobSeekerResetPasswordController::class, 'showResetForm'])->name('password.reset');

        Route::middleware('auth:jobseeker')->group(function() {
            Route::get('home', [JobSeekerHomeController::class, 'index'])->name('home');

            Route::get('profile', [JobSeekerProfileController::class, 'index'])->name('profile');
            Route::put('profile/update', [JobSeekerProfileController::class, 'update'])->name('profile.update');
            Route::put('profile/picture/delete', [JobSeekerProfileController::class, 'destroyPhoto'])->name('profile.picture.delete');

            Route::get('education', [JobSeekerEducationController::class, 'index'])->name('education');

            Route::get('experience', [JobSeekerExperienceController::class, 'index'])->name('experience');

            Route::get('resume', [JobSeekerResumeController::class, 'index'])->name('resume');
        });
    });

    Route::prefix('company')->name('company.')->group(function() {
        Route::namespace('Auth')->group(function() {
            Route::get('register', [CompanyRegisterController::class, 'viewRegister'])->name('register.view');
            Route::post('register', [CompanyRegisterController::class, 'register'])->name('register');
    
            Route::get('login', [CompanyLoginController::class, 'viewlogin'])->name('login.view');
            Route::post('login', [CompanyLoginController::class, 'login'])->name('login');

            Route::post('logout', [CompanyLoginController::class, 'logout'])->name('logout');

            Route::get('password/reset', [CompanyForgotPasswordController::class, 'viewRequestForm'])->name('password.request');
            Route::post('password/email', [CompanyForgotPasswordController::class, 'sendResetLink'])->name('password.email');

            Route::get('password/reset/{token}', [CompanyResetPasswordController::class, 'viewResetForm'])->name('password.reset');
            Route::post('password/reset', [CompanyResetPasswordController::class, 'updatePassword'])->name('password.update');
        });
        
        Route::middleware('auth:company')->group(function() {
            Route::get('home', [CompanyHomeController::class, 'index'])->name('home');
        });
    });

?>

routes/web.php
<?php

use App\Http\Controllers\Admin\AdminRoleController;
use App\Http\Controllers\Admin\AdminUserController;
use App\Http\Controllers\Admin\CompanyIndustryController;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\JobCategoryController;
use App\Http\Controllers\Admin\JobSeekerController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['register' => false]);

Route::middleware('auth')->prefix('admin')->name('admin.')->group(function() {
    Route::get('/home', [HomeController::class, 'index'])->name('home');
    
    Route::resource('users', AdminUserController::class);
    Route::get('users/{user}/reset-password', [AdminUserController::class, 'showResetForm'])->name('users.password.show');
    Route::put('users/{user}/resets', [AdminUserController::class, 'resetPassword'])->name('users.password.reset');

    Route::resource('roles', AdminRoleController::class);

    Route::resource('jobcategories', JobCategoryController::class);
    Route::get('jobcategories/create/checkSlug', [JobCategoryController::class, 'checkSlug'])->name('jobcategory.checkSlug');

    Route::resource('jobseekers', JobSeekerController::class);
    
    Route::resource('companyindustries', CompanyIndustryController::class);
});

include('frontend.php');

app/Http/Controllers/Frontend/Company/CompanyHomeController.php
<?php

namespace App\Http\Controllers\Frontend\Company;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class CompanyHomeController extends Controller
{
    public function index()
    {
        return view('frontend.companies.home');
    }
}

app/Http/Controllers/Frontend/JobSeeker/JobSeekerEducationController.php
<?php

namespace App\Http\Controllers\Frontend\JobSeeker;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class JobSeekerEducationController extends Controller
{
    public function index()
    {
        return view('frontend.jobseekers.education');
    }
}

app/Http/Controllers/Frontend/JobSeeker/JobSeekerExperienceController.php
<?php

namespace App\Http\Controllers\Frontend\JobSeeker;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class JobSeekerExperienceController extends Controller
{
    public function index()
    {
        return view('frontend.jobseekers.experience');
    }
}

app/Http/Controllers/Frontend/JobSeeker/JobSeekerHomeController.php
<?php

namespace App\Http\Controllers\Frontend\JobSeeker;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class JobSeekerHomeController extends Controller
{
    public function index()
    {
        return view('frontend.jobseekers.home');
    }
}

app/Http/Controllers/Frontend/JobSeeker/JobSeekerProfileController.php
<?php

namespace App\Http\Controllers\Frontend\JobSeeker;

use App\Http\Controllers\Controller;
use App\Http\Requests\JobSeekerRequest;
use App\Models\JobCategory;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\File;

class JobSeekerProfileController extends Controller
{
    public function jobseeker()
    {
        return Auth::guard('jobseeker')->user();
    }

    public function index()
    {   
        $job_categories = JobCategory::where('status', 1)->get();

        if ($this->jobseeker()->profile_picture && File::exists('images/jobseeker/'.$this->jobseeker()->profile_picture)) {
            $image = 'jobseeker/'.$this->jobseeker()->profile_picture;
        }
        else {
            $image = 'no-image.png';
        }

        return view('frontend.jobseekers.profile')->with([
            'jobseeker' => $this->jobseeker(),
            'image' => $image,
            'job_categories' => $job_categories,
        ]);
    }

    public function update(JobSeekerRequest $request)
    {
        // CHECK IF IMAGE HAS IMAGE BEFORE UPDATING

        if ($request->hasFile('profile_picture')) {
            if ($this->jobseeker()->profile_picture) {
                $destination = 'images/jobseeker/'.$this->jobseeker()->profile_picture;
                if (File::exists($destination)) {
                    unlink($destination);
                }
            }
            $file = $request->file('profile_picture');
            $extension = $file->getClientOriginalExtension();
            $fileName = time().'.'.$extension;
            $file->move('images/jobseeker/', $fileName);

            $this->jobseeker()->update($request->safe()->except(['profile_picture']) + ['profile_picture' => $fileName]);
        }
        else {
            $this->jobseeker()->update($request->validated());
        }

        return redirect()->route('jobseeker.profile')->with('success', 'Your Profile has been Updated!!');
    }

    public function destroyPhoto()
    {
        // IF FILE EXISTS IN DB AND PUBLIC FOLDER UNLINK

        if ($this->jobseeker()->profile_picture) {
            $destination = 'images/jobseeker/'.$this->jobseeker()->profile_picture;
            if (File::exists($destination)) {
                unlink($destination);
            }
        }

        $this->jobseeker()->update(['profile_picture' => NULL]);

        return redirect()->route('jobseeker.profile')->with('success', 'Your Photo has been deleted!!');
    }
}

app/Http/Controllers/Frontend/JobSeeker/JobSeekerResumeController.php
<?php

namespace App\Http\Controllers\Frontend\JobSeeker;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class JobSeekerResumeController extends Controller
{
    public function index()
    {
        return view('frontend.jobseekers.resume');
    }
}

resources/views/frontend/layouts/alert.blade.php
{{-- Success Alert --}}
@if (session('success'))
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        {{ session('success') }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
@endif

{{-- Error Alert --}}
@if (session('error'))
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        {{ session('error') }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
@endif

{{-- Error Alert --}}
@if (session('status'))
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        {{ session('status') }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
@endif

resources/views/frontend/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">

@include('frontend.layouts.header')

<body>
    <div class="container-xxl bg-white p-0">
        <!-- Spinner Start -->
        <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <!-- Spinner End -->

        @include('frontend.layouts.navbar')
        
        @yield('content')

        @include('frontend.layouts.footer')
    </div>  
</body>

</html>

resources/views/frontend/layouts/dash-app.blade.php
<!DOCTYPE html>
<html lang="en">

@include('frontend.layouts.header')

<body>
    <div class="container-xxl bg-white p-0">
        <!-- Spinner Start -->
        <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <!-- Spinner End -->

        @include('frontend.layouts.navbar')
        
        <div id="layoutSidenav">
            <div id="layoutSidenav_nav">
                <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                    <div class="sb-sidenav-menu">
                        <div class="nav">
                            <div class="sb-sidenav-menu-heading">Dashboard</div>
                            <a class="nav-link {{ (request()->segment(2) == 'profile') ? 'active' : '' }}" href="{{ route('jobseeker.profile') }}">
                                <div class="sb-nav-link-icon"><i class="fa-solid fa-user"></i></div>
                                Profile
                            </a>
                            <a class="nav-link {{ (request()->segment(2) == 'education') ? 'active' : '' }}" href="{{ route('jobseeker.education') }}">
                                <div class="sb-nav-link-icon"><i class="fa-solid fa-graduation-cap"></i></div>
                                Education
                            </a>
                            <a class="nav-link {{ (request()->segment(2) == 'experience') ? 'active' : '' }}" href="{{ route('jobseeker.experience') }}">
                                <div class="sb-nav-link-icon"><i class="fa-solid fa-briefcase"></i></div>
                                Experience
                            </a>
                            <a class="nav-link {{ (request()->segment(2) == 'resume') ? 'active' : '' }}" href="{{ route('jobseeker.resume') }}">
                                <div class="sb-nav-link-icon"><i class="fa-solid fa-file"></i></div>
                                Resume
                            </a>
                        </div>
                    </div>
                </nav>
            </div>
            @yield('content')
        </div>        

        @include('frontend.layouts.footer')
    </div>  
</body>

</html>

resources/views/frontend/layouts/footer.blade.php
<!-- Footer Start -->
<div class="container-fluid bg-dark text-white-50 footer pt-5 mt-5 wow fadeIn" data-wow-delay="0.1s">
    <div class="container py-5">
        <div class="row g-5">
            <div class="col-lg-3 col-md-6">
                <h5 class="text-white mb-4">Company</h5>
                <a class="btn btn-link text-white-50" href="">About Us</a>
                <a class="btn btn-link text-white-50" href="">Contact Us</a>
                <a class="btn btn-link text-white-50" href="">Our Services</a>
                <a class="btn btn-link text-white-50" href="">Privacy Policy</a>
                <a class="btn btn-link text-white-50" href="">Terms & Condition</a>
            </div>
            <div class="col-lg-3 col-md-6">
                <h5 class="text-white mb-4">Quick Links</h5>
                <a class="btn btn-link text-white-50" href="">About Us</a>
                <a class="btn btn-link text-white-50" href="">Contact Us</a>
                <a class="btn btn-link text-white-50" href="">Our Services</a>
                <a class="btn btn-link text-white-50" href="">Privacy Policy</a>
                <a class="btn btn-link text-white-50" href="">Terms & Condition</a>
            </div>
            <div class="col-lg-3 col-md-6">
                <h5 class="text-white mb-4">Contact</h5>
                <p class="mb-2"><i class="fa fa-map-marker-alt me-3"></i>123 Street, New York, USA</p>
                <p class="mb-2"><i class="fa fa-phone-alt me-3"></i>+012 345 67890</p>
                <p class="mb-2"><i class="fa fa-envelope me-3"></i>info@example.com</p>
                <div class="d-flex pt-2">
                    <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-twitter"></i></a>
                    <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-facebook-f"></i></a>
                    <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-youtube"></i></a>
                    <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-linkedin-in"></i></a>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <h5 class="text-white mb-4">Newsletter</h5>
                <p>Dolor amet sit justo amet elitr clita ipsum elitr est.</p>
                <div class="position-relative mx-auto" style="max-width: 400px;">
                    <input class="form-control bg-transparent w-100 py-3 ps-4 pe-5" type="text" placeholder="Your email">
                    <button type="button" class="btn btn-primary py-2 position-absolute top-0 end-0 mt-2 me-2">SignUp</button>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="copyright">
            <div class="row">
                <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                    &copy; <a class="border-bottom" href="#">Your Site Name</a>, All Right Reserved. 
                    
                    <!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
                    Designed By <a class="border-bottom" href="https://htmlcodex.com">HTML Codex</a>
                </div>
                <div class="col-md-6 text-center text-md-end">
                    <div class="footer-menu">
                        <a href="">Home</a>
                        <a href="">Cookies</a>
                        <a href="">Help</a>
                        <a href="">FQAs</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Footer End -->


<!-- Back to Top -->
<a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
</div>

<!-- JavaScript Libraries -->
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
{{-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script> --}}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
<script src="{{ asset('js/scripts.js') }}"></script>
<script src="lib/wow/wow.min.js"></script>
<script src="lib/easing/easing.min.js"></script>
<script src="lib/waypoints/waypoints.min.js"></script>
<script src="lib/owlcarousel/owl.carousel.min.js"></script>

<!-- Template Javascript -->
<script src="{{ asset('js/main.js') }}"></script>

resources/views/frontend/layouts/header.blade.php
<head>
    <meta charset="utf-8">
    <title>JobEntry - @yield('title')</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Inter:wght@700;800&display=swap" rel="stylesheet">
    
    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="lib/animate/animate.min.css" rel="stylesheet">
    <link href="lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{{ asset('css/bootstrap.min.css') }}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{{ asset('css/style.css') }}" rel="stylesheet">
    
    <link href="{{ asset('css/styles.css') }}" rel="stylesheet" />
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
</head>

resources/views/frontend/layouts/navbar.blade.php
<!-- Navbar Start -->
<nav class="navbar navbar-expand-lg bg-white navbar-light shadow sticky-top p-0">
    <a href="{{ route('index') }}" class="navbar-brand d-flex align-items-center text-center py-0 px-4 px-lg-5">
        <h1 class="m-0 text-primary">JobEntry</h1>
    </a>
    <button type="button" class="navbar-toggler me-4" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <div class="navbar-nav ms-auto p-4 p-lg-0">
            <a href="{{ route('index') }}" class="nav-item nav-link">Home</a>
            <a href="about.html" class="nav-item nav-link">About</a>
            <div class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Jobs</a>
                <div class="dropdown-menu rounded-0 m-0">
                    <a href="job-list.html" class="dropdown-item">Job List</a>
                    <a href="job-detail.html" class="dropdown-item">Job Detail</a>
                </div>
            </div>
            <div class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Pages</a>
                <div class="dropdown-menu rounded-0 m-0">
                    <a href="category.html" class="dropdown-item">Job Category</a>
                    <a href="testimonial.html" class="dropdown-item">Testimonial</a>
                    <a href="404.html" class="dropdown-item">404</a>
                </div>
            </div>
            <a href="contact.html" class="nav-item nav-link">Contact</a>
        </div>
        @if (Auth::guard('jobseeker')->check())    
            <div class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                    {{ Auth::guard('jobseeker')->user()->name }}<span class="caret"></span>
                </a>
                <div class="dropdown-menu rounded-0 m-0">
                    <a href="{{ route('jobseeker.profile') }}" class="dropdown-item">My Profile</a>
                    <form action="{{ route('jobseeker.logout') }}" method="POST">
                    @csrf
                    <button class="dropdown-item">Logout</button>
                    </form>
                </div>
            </div>
        @elseif (Auth::guard('company')->check())    
            <div class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                    {{ Auth::guard('company')->user()->name }}<span class="caret"></span>
                </a>
                <div class="dropdown-menu rounded-0 m-0">
                    <a href="{{ route('company.home') }}" class="dropdown-item">Dashboard</a>
                    <form action="{{ route('company.logout') }}" method="POST">
                    @csrf
                    <button class="dropdown-item">Logout</button>
                    </form>
                </div>
            </div>
        @elseif (Auth::check())
            <div class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                    {{ Auth::user()->name }}<span class="caret"></span>
                </a>
                <div class="dropdown-menu rounded-0 m-0">
                    <a href="{{ route('admin.home') }}" class="dropdown-item">Admin Panel</a>
                    <form action="{{ route('logout') }}" method="POST">
                    @csrf
                    <button class="dropdown-item">Logout</button>
                    </form>
                </div>
            </div>
        @else
            <div class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Job Seeker</a>
                <div class="dropdown-menu rounded-0 m-0">
                    <a href="{{ route('jobseeker.login.view') }}" class="dropdown-item">Login</a>
                    <a href="{{ route('jobseeker.register.view') }}" class="dropdown-item">Register</a>
                </div>
            </div>

            <div class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Company</a>
                <div class="dropdown-menu rounded-0 m-0">
                    <a href="{{ route('company.login.view') }}" class="dropdown-item">Login</a>
                    <a href="{{ route('company.register.view') }}" class="dropdown-item">Register</a>
                </div>
            </div>
            <a href="{{ route('login') }}" class="nav-item nav-link">Admin</a>
        @endif        
    </div>
</nav>
<!-- Navbar End -->