routes/frontend.php
<?php

use App\Http\Controllers\Frontend\Company\Auth\CompanyForgotPasswordController;
use App\Http\Controllers\Frontend\Company\Auth\CompanyLoginController;
use App\Http\Controllers\Frontend\Company\Auth\CompanyRegisterController;
use App\Http\Controllers\Frontend\Company\Auth\CompanyResetPasswordController;
use App\Http\Controllers\Frontend\Company\CompanyHomeController;
use App\Http\Controllers\Frontend\JobSeeker\Auth\JobSeekerForgotPasswordController;
use App\Http\Controllers\Frontend\JobSeeker\Auth\JobSeekerLoginController;
use App\Http\Controllers\Frontend\JobSeeker\Auth\JobSeekerRegisterController;
use App\Http\Controllers\Frontend\JobSeeker\Auth\JobSeekerResetPasswordController;
use App\Http\Controllers\Frontend\JobSeeker\JobSeekerEducationController;
use App\Http\Controllers\Frontend\JobSeeker\JobSeekerExperienceController;
use App\Http\Controllers\Frontend\JobSeeker\JobSeekerHomeController;
use App\Http\Controllers\Frontend\JobSeeker\JobSeekerProfileController;
use App\Http\Controllers\Frontend\JobSeeker\JobSeekerResumeController;
use Illuminate\Support\Facades\Route;

    Route::get('/', function () {
        return view('frontend.index');
    })->name('index');

    Route::prefix('jobseeker')->name('jobseeker.')->group(function() {
        Route::get('register', [JobSeekerRegisterController::class, 'viewRegister'])->name('register.view');
        Route::post('register', [JobSeekerRegisterController::class, 'register'])->name('register');
        
        Route::get('login', [JobSeekerLoginController::class, 'viewlogin'])->name('login.view');
        Route::post('login', [JobSeekerLoginController::class, 'login'])->name('login');

        Route::post('logout', [JobSeekerLoginController::class, 'logout'])->name('logout');

        Route::post('password/email', [JobSeekerForgotPasswordController::class, 'sendResetLinkEmail'])->name('password.email');
        Route::get('password/reset', [JobSeekerForgotPasswordController::class, 'showLinkRequestForm'])->name('password.request');

        Route::post('password/reset', [JobSeekerResetPasswordController::class, 'reset']);
        Route::get('password/reset/{token}', [JobSeekerResetPasswordController::class, 'showResetForm'])->name('password.reset');

        Route::middleware('auth:jobseeker')->group(function() {
            Route::get('home', [JobSeekerHomeController::class, 'index'])->name('home');

            Route::get('profile', [JobSeekerProfileController::class, 'index'])->name('profile');
            Route::put('profile/update', [JobSeekerProfileController::class, 'update'])->name('profile.update');
            Route::put('profile/picture/delete', [JobSeekerProfileController::class, 'destroyPhoto'])->name('profile.picture.delete');

            Route::get('education', [JobSeekerEducationController::class, 'index'])->name('education');

            Route::get('experience', [JobSeekerExperienceController::class, 'index'])->name('experience');

            Route::get('resume', [JobSeekerResumeController::class, 'index'])->name('resume');
        });
    });

    Route::prefix('company')->name('company.')->group(function() {
        Route::namespace('Auth')->group(function() {
            Route::get('register', [CompanyRegisterController::class, 'viewRegister'])->name('register.view');
            Route::post('register', [CompanyRegisterController::class, 'register'])->name('register');
    
            Route::get('login', [CompanyLoginController::class, 'viewlogin'])->name('login.view');
            Route::post('login', [CompanyLoginController::class, 'login'])->name('login');

            Route::post('logout', [CompanyLoginController::class, 'logout'])->name('logout');

            Route::get('password/reset', [CompanyForgotPasswordController::class, 'viewRequestForm'])->name('password.request');
            Route::post('password/email', [CompanyForgotPasswordController::class, 'sendResetLink'])->name('password.email');

            Route::get('password/reset/{token}', [CompanyResetPasswordController::class, 'viewResetForm'])->name('password.reset');
            Route::post('password/reset', [CompanyResetPasswordController::class, 'updatePassword'])->name('password.update');
        });
        
        Route::middleware('auth:company')->group(function() {
            Route::get('home', [CompanyHomeController::class, 'index'])->name('home');
        });
    });

?>

routes/web.php
<?php

use App\Http\Controllers\Admin\AdminRoleController;
use App\Http\Controllers\Admin\AdminUserController;
use App\Http\Controllers\Admin\CompanyIndustryController;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\JobCategoryController;
use App\Http\Controllers\Admin\JobSeekerController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['register' => false]);

Route::middleware('auth')->prefix('admin')->name('admin.')->group(function() {
    Route::get('/home', [HomeController::class, 'index'])->name('home');
    
    Route::resource('users', AdminUserController::class);
    Route::get('users/{user}/reset-password', [AdminUserController::class, 'showResetForm'])->name('users.password.show');
    Route::put('users/{user}/resets', [AdminUserController::class, 'resetPassword'])->name('users.password.reset');

    Route::resource('roles', AdminRoleController::class);

    Route::resource('jobcategories', JobCategoryController::class);
    Route::get('jobcategories/create/checkSlug', [JobCategoryController::class, 'checkSlug'])->name('jobcategory.checkSlug');

    Route::resource('jobseekers', JobSeekerController::class);
    
    Route::resource('companyindustries', CompanyIndustryController::class);
});

include('frontend.php');

app/Http/Controllers/Admin/AdminUserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\AdminUserPasswordRequest;
use App\Http\Requests\AdminUserRequest;
use Spatie\Permission\Models\Role;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class AdminUserController extends Controller
{
    public function __construct()
    {
        $this->middleware('permission:user-list|user-create|user-edit|user-delete|user-password-reset', ['only' => ['index', 'show']]);
        $this->middleware('permission:user-create', ['only' => ['create', 'store']]);
        $this->middleware('permission:user-edit', ['only' => ['edit', 'update']]);
        $this->middleware('permission:user-delete', ['only' => ['destroy']]);
        $this->middleware('permission:user-password-reset', ['only' => ['showResetForm', 'resetPassword']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request, User $user)
    {
        $keyword = $request->query('keyword');
        $queryRole = $request->query('role');
        
        // SEARCH USING KEYWORD AND ROLE
        $users = $this->search($keyword, $queryRole);

        $allRoles = Role::all();

        return view('admin.adminuser.index', compact('users', 'allRoles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = Role::all();

        return view('admin.adminuser.create', compact('roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(AdminUserRequest $request)
    {
        $user = User::create([
            'name' => $request->name,
            'username' => $request->username,
            'email' => $request->email,
            'phone' => $request->phone,
            'password' => bcrypt('password'),
        ]);

        $user->assignRole($request->input('roles'));

        return redirect()->route('admin.users.index')->with('success', 'User '.$user->name.' has been created!!!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        $roles = Role::all();
        $userRole = $user->roles->first();

        return view('admin.adminuser.edit', compact('user', 'roles', 'userRole'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  User $user
     * @return \Illuminate\Http\Response
     */
    public function update(AdminUserRequest $request, User $user)
    {
        $user->update($request->validated());
        
        // MODEL ROLE DELETING FROM TABLE BEFORE UPDATING WITH NEW VALUE

        DB::table('model_has_roles')->where('model_id', $user->id)->delete();

        $user->assignRole($request->input('roles'));

        return redirect()->route('admin.users.index')->with('status', $user->name.' has been Updated!!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->delete();

        return redirect()->route('admin.users.index')->with('error', 'User '.$user->name.' has been deleted!!!');
    }

    /**
     * Show reset password Form for user.
     *
     * @param  int  $user
     * @return \Illuminate\Http\Response
     */
    public function showResetForm(User $user)
    {
        return view('admin.adminuser.reset-password', compact('user'));
    }

    /**
     * Resets the password of user.
     *
     * @param  int  $user
     * @return \Illuminate\Http\Response
     */
    public function resetPassword(AdminUserPasswordRequest $request, User $user)
    {
        // $hashedPassword = $user->password;

        // PASSWORD RESET FUNCTION

        // if (Hash::check($request->old_password, $hashedPassword)) { 

            $user->password = Hash::make($request->password);
            $user->update(['password' => $user->password]);

            return redirect()->route('admin.users.index')->with('success', 'Password of '.$user->name.' has been reset successfully!!!');
        // }
    }

    // SEARCH FUNCTION FOR QUERYING
    public function search($keyword, $queryRole)
    {
        if (empty($keyword) && empty($queryRole))
        {
            $users = User::orderBy('id','ASC')->get();
        }
        elseif (empty($keyword)) {
            $users = User::whereHas('roles', function($q) use($queryRole){
                $q->whereId($queryRole);
            })->get();
        }
        elseif (empty($queryRole)) {
            $users = User::where('name', 'LIKE', "%$keyword%")->get();
        }
        elseif (!empty($keyword) && !empty($queryRole)) {
            $users = User::where('name', 'LIKE', "%$keyword%")
                ->WhereHas('roles', function($q) use($queryRole) {
                    $q->whereId($queryRole);
                })->get();
        }

        return $users;
    }
}

resources/views/admin/adminuser/create.blade.php
@extends('layouts.app')

@section('content')
<div id="layoutSidenav_content">
    <main>
        <div class="container-fluid px-4">
            <h1 class="mt-4">Admin Users</h1>
            <ol class="breadcrumb mb-4">
                <li class="breadcrumb-item"><a href="{{ route('admin.home') }}">Dashboard</a></li>
                <li class="breadcrumb-item"><a href="{{ route('admin.users.index') }}">Users</a></li>
                <li class="breadcrumb-item active">Create</li>
            </ol>
            <div class="d-flex justify-content-center">
                <div class="card mb-4 w-50 ">
                    <div class="card-header">
                        <i class="fas fa-table me-1"></i>
                        Create Admin Users
                    </div>
                    <div class="card-body">
                        <form action="{{ route('admin.users.store') }}" method="POST">
                            @csrf
                            <div class="form-floating mb-3">
                                <input class="form-control @error('name') is-invalid @enderror" id="inputname" type="text" placeholder="Name" name="name" value="{{ old('name') }}">
                                <label for="inputname">Name</label>
                                @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                            <div class="form-floating mb-3">
                                <input class="form-control @error('username') is-invalid @enderror" id="inputusername" type="text" placeholder="username" name="username" value="{{ old('username') }}">
                                <label for="inputusername">Username</label>
                                @error('username')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                            <div class="form-floating mb-3">
                                <input class="form-control @error('email') is-invalid @enderror" id="inputemail" type="email" placeholder="email" name="email" value="{{ old('email') }}">
                                <label for="inputemail">Email</label>
                                @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                            <div class="form-floating mb-3">
                                <input class="form-control @error('password') is-invalid @enderror" id="inputpassword" type="password" placeholder="password" name="password">
                                <label for="inputpassword">Password</label>
                                @error('password')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                            <div class="form-floating mb-3">
                                <input class="form-control @error('phone') is-invalid @enderror" id="inputphone" type="text" placeholder="phone" name="phone" value="{{ old('phone') }}" />
                                <label for="inputphone">Phone</label>
                                @error('phone')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                            <div class="form-floating mb-3">
                                <select class="form-control @error('roles') is-invalid @enderror" id="inputrole" placeholder="role" name="roles">
                                <label for="inputrole">Role</label>
                                <option disabled selected>Select Role</option>
                                @foreach ($roles as $role)
                                    @if (Auth::user()->hasRole('SuperAdmin'))
                                        <option value="{{ $role->name }}" {{ (old('roles') == $role->name) ? 'selected' : '' }}>{{ $role->name }}</option>
                                    @else
                                        @if ($role->name != 'SuperAdmin')
                                            <option value="{{ $role->name }}" {{ (old('roles') == $role->name) ? 'selected' : '' }}>{{ $role->name }}</option>
                                        @endif
                                    @endif                             
                                @endforeach

                                @error('roles')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                                </select>
                            </div>
                            <div class="mt-4 mb-0 d-flex justify-content-center">
                                <div class="d-grid w-25"><button type="submit" class="btn btn-primary btn-block">Create</button></div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </main>
</div>
@endsection

resources/views/admin/adminuser/edit.blade.php
@extends('layouts.app')

@section('content')
<div id="layoutSidenav_content">
    <main>
        <div class="container-fluid px-4">
            <h1 class="mt-4">Admin Users</h1>
            <ol class="breadcrumb mb-4">
                <li class="breadcrumb-item"><a href="{{ route('admin.home') }}">Dashboard</a></li>
                <li class="breadcrumb-item"><a href="{{ route('admin.users.index') }}">Users</a></li>
                <li class="breadcrumb-item">{{ $user->name }}</li>
                <li class="breadcrumb-item active">Edit</li>
            </ol>
            <div class="d-flex justify-content-center">
                <div class="card mb-4 w-50 ">
                    <div class="card-header">
                        <i class="fas fa-table me-1"></i>
                        Edit Admin Users
                    </div>
                    <div class="card-body">
                        <form action="{{ route('admin.users.update', $user->id) }}" method="POST">
                            @csrf
                            @method('PUT')
                            <div class="form-floating mb-3">
                                <input class="form-control @error('name') is-invalid @enderror" id="inputname" type="text" placeholder="Name" name="name" value="{{ old('name') ?? $user->name }}"/>
                                <label for="inputname">Name</label>
                                @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                            <div class="form-floating mb-3">
                                <input class="form-control @error('username') is-invalid @enderror" id="inputusername" type="text" placeholder="username" name="username" value="{{ old('username') ?? $user->username }}" />
                                <label for="inputusername">Username</label>
                                @error('username')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                            <div class="form-floating mb-3">
                                <input class="form-control @error('email') is-invalid @enderror" id="inputemail" type="email" placeholder="email" name="email" value="{{ old('email') ?? $user->email }}" />
                                <label for="inputemail">Email</label>
                                @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                            <div class="form-floating mb-3">
                                <input class="form-control @error('phone') is-invalid @enderror" id="inputphone" type="text" placeholder="phone" name="phone" value="{{ old('phone') ?? $user->phone }}" />
                                <label for="inputphone">Phone</label>
                                @error('phone')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                            <div class="form-floating mb-3">
                                <select class="form-control @error('roles') is-invalid @enderror" id="inputrole" type="role" placeholder="role" name="roles">
                                <label for="inputrole">Role</label>
                                <option disabled selected>Select Role</option>
                                
                                @foreach ($roles as $role)
                                    @if (Auth::user()->hasRole(1))
                                        @if (!empty($userRole)) 
                                            <option value="{{ $role->name }}" @if (old('roles') || $userRole->name == $role->name) selected @endif>{{ $role->name }}</option>
                                        @else
                                            <option value="{{ $role->name }}" @if(old('roles')) selected @endif>{{ $role->name }}</option>
                                        @endif
                                    @else
                                        @if ($role->id != 1)
                                            @if (!empty($userRole))
                                                <option value="{{ $role->name }}" @if (old('roles') || $userRole->name == $role->name) selected @endif>{{ $role->name }}</option>
                                            @else 
                                                <option value="{{ $role->name }}" @if (old('roles')) selected @endif>{{ $role->name }}</option>
                                            @endif
                                        @endif
                                    @endif
                                @endforeach
                                @error('roles')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror  
                                
                                </select>
                            </div>
                            <div class="mt-4 mb-0 d-flex justify-content-center">
                                <div class="d-grid w-25"><button type="submit" class="btn btn-primary btn-block">Update</button></div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </main>
</div>
@endsection

resources/views/admin/adminuser/index.blade.php
@extends('layouts.app')

@section('content')
<div id="layoutSidenav_content">
    <main>
        <div class="container-fluid px-4">
            <h1 class="mt-4">Admin Users</h1>
            <ol class="breadcrumb mb-4">
                <li class="breadcrumb-item"><a href="{{ route('admin.home') }}">Dashboard</a></li>
                <li class="breadcrumb-item active">Users</li>
            </ol>  
            @include('frontend.layouts.alert')
            <div class="mb-4">
                <form action="" class="row g-3">
                    <div class="col-sm-3">
                        <input type="search" name="keyword" class="form-control" placeholder="Search" aria-label="Search" value="{{ request()->query('keyword') }}">
                    </div>
                    <div class="col-sm-2">
                        <select type="search" name="role" class="form-control" placeholder="Search" aria-label="Search">
                            <option value="{{ NULL }}">Select Role</option>
                            @foreach ($allRoles as $role)
                                <option value="{{ $role->id }}" {{ request()->query('role') == $role->id ? 'selected' : '' }}>{{ $role->name }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="col-sm-2">
                        <button class="btn btn-primary me-1"><i class="fa fa-search me-1" aria-hidden="true"></i>Search</button>

                        <a href="{{ route('admin.users.index') }}">
                            <button type="button" class="btn btn-danger"><i class="fa-solid fa-backward me-1"></i></i>Reset</button>
                        </a>
                    </div>
                </form>
            </div>
            <div class="card mb-4">
                <div class="card-header">
                    <i class="fas fa-table me-1"></i>
                    Admin Users
                    @can('user-create')
                    <a class="btn btn-success float-end" href ="{{ route('admin.users.create') }}"><i class="fa-solid fa-plus"></i>
                        Add User
                    </a>
                    @endcan
                </div>
                <div class="card-body">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th class="col-1">S.N.</th>
                                <th class="col-2">Name</th>
                                <th class="col-2">Email</th>
                                <th class="col-2">Role</th>
                                <th class="col-3">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse ($users as $user)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $user->name }}</td>
                                <td>{{ $user->email }}</td>
                                <td>
                                    <label class="badge bg-secondary">{{ $user->getRoleNames()->first() }}</label>
                                </td>
                                <td class="d-flex justify-content-start">
                                    @if(!$user->hasRole(['SuperAdmin']))
                                        @can('user-edit')
                                            <a class="btn btn-sm btn-warning me-1" href="{{ route('admin.users.edit', $user->id) }}"><i class="fa-solid fa-pen-to-square me-1"></i>Edit</a>
                                        @endcan
                                        @can('user-delete')
                                            <form action="{{ route('admin.users.destroy', $user->id) }}" method="POST" class="">
                                            @csrf
                                            @method('DELETE')
                                                <button type="submit" class="btn btn-sm btn-danger me-1"><i class="fa-solid fa-trash-can me-1"></i>Delete</button>
                                            </form>      
                                        @endcan
                                        @can('user-password-reset')
                                            <a class="btn btn-sm btn-success" href="{{ route('admin.users.password.show', $user->id) }}"><i class="fa-solid fa-arrows-rotate me-1"></i>Reset Password</a>
                                        @endcan
                                    @endif
                                </td>
                            </tr>
                            @empty
                                <tr>
                                    <td></td>
                                    <td>No Results Found</td>
                                </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </main>
</div>
@endsection