routes/frontend.php
<?php

use App\Http\Controllers\Frontend\Company\Auth\CompanyForgotPasswordController;
use App\Http\Controllers\Frontend\Company\Auth\CompanyLoginController;
use App\Http\Controllers\Frontend\Company\Auth\CompanyRegisterController;
use App\Http\Controllers\Frontend\Company\Auth\CompanyResetPasswordController;
use App\Http\Controllers\Frontend\Company\CompanyHomeController;
use App\Http\Controllers\Frontend\JobSeeker\Auth\JobSeekerForgotPasswordController;
use App\Http\Controllers\Frontend\JobSeeker\Auth\JobSeekerLoginController;
use App\Http\Controllers\Frontend\JobSeeker\Auth\JobSeekerRegisterController;
use App\Http\Controllers\Frontend\JobSeeker\Auth\JobSeekerResetPasswordController;
use App\Http\Controllers\Frontend\JobSeeker\JobSeekerEducationController;
use App\Http\Controllers\Frontend\JobSeeker\JobSeekerExperienceController;
use App\Http\Controllers\Frontend\JobSeeker\JobSeekerHomeController;
use App\Http\Controllers\Frontend\JobSeeker\JobSeekerProfileController;
use App\Http\Controllers\Frontend\JobSeeker\JobSeekerResumeController;
use Illuminate\Support\Facades\Route;

    Route::get('/', function () {
        return view('frontend.index');
    })->name('index');

    Route::prefix('jobseeker')->name('jobseeker.')->group(function() {
        Route::get('register', [JobSeekerRegisterController::class, 'viewRegister'])->name('register.view');
        Route::post('register', [JobSeekerRegisterController::class, 'register'])->name('register');
        
        Route::get('login', [JobSeekerLoginController::class, 'viewlogin'])->name('login.view');
        Route::post('login', [JobSeekerLoginController::class, 'login'])->name('login');

        Route::post('logout', [JobSeekerLoginController::class, 'logout'])->name('logout');

        Route::post('password/email', [JobSeekerForgotPasswordController::class, 'sendResetLinkEmail'])->name('password.email');
        Route::get('password/reset', [JobSeekerForgotPasswordController::class, 'showLinkRequestForm'])->name('password.request');

        Route::post('password/reset', [JobSeekerResetPasswordController::class, 'reset']);
        Route::get('password/reset/{token}', [JobSeekerResetPasswordController::class, 'showResetForm'])->name('password.reset');

        Route::middleware('auth:jobseeker')->group(function() {
            Route::get('home', [JobSeekerHomeController::class, 'index'])->name('home');

            Route::get('profile', [JobSeekerProfileController::class, 'index'])->name('profile');
            Route::put('profile/update', [JobSeekerProfileController::class, 'update'])->name('profile.update');
            Route::put('profile/picture/delete', [JobSeekerProfileController::class, 'destroyPhoto'])->name('profile.picture.delete');

            Route::get('education', [JobSeekerEducationController::class, 'index'])->name('education');

            Route::get('experience', [JobSeekerExperienceController::class, 'index'])->name('experience');

            Route::get('resume', [JobSeekerResumeController::class, 'index'])->name('resume');
        });
    });

    Route::prefix('company')->name('company.')->group(function() {
        Route::namespace('Auth')->group(function() {
            Route::get('register', [CompanyRegisterController::class, 'viewRegister'])->name('register.view');
            Route::post('register', [CompanyRegisterController::class, 'register'])->name('register');
    
            Route::get('login', [CompanyLoginController::class, 'viewlogin'])->name('login.view');
            Route::post('login', [CompanyLoginController::class, 'login'])->name('login');

            Route::post('logout', [CompanyLoginController::class, 'logout'])->name('logout');

            Route::get('password/reset', [CompanyForgotPasswordController::class, 'viewRequestForm'])->name('password.request');
            Route::post('password/email', [CompanyForgotPasswordController::class, 'sendResetLink'])->name('password.email');

            Route::get('password/reset/{token}', [CompanyResetPasswordController::class, 'viewResetForm'])->name('password.reset');
            Route::post('password/reset', [CompanyResetPasswordController::class, 'updatePassword'])->name('password.update');
        });
        
        Route::middleware('auth:company')->group(function() {
            Route::get('home', [CompanyHomeController::class, 'index'])->name('home');
        });
    });

?>

routes/web.php
<?php

use App\Http\Controllers\Admin\AdminRoleController;
use App\Http\Controllers\Admin\AdminUserController;
use App\Http\Controllers\Admin\CompanyIndustryController;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\JobCategoryController;
use App\Http\Controllers\Admin\JobSeekerController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['register' => false]);

Route::middleware('auth')->prefix('admin')->name('admin.')->group(function() {
    Route::get('/home', [HomeController::class, 'index'])->name('home');
    
    Route::resource('users', AdminUserController::class);
    Route::get('users/{user}/reset-password', [AdminUserController::class, 'showResetForm'])->name('users.password.show');
    Route::put('users/{user}/resets', [AdminUserController::class, 'resetPassword'])->name('users.password.reset');

    Route::resource('roles', AdminRoleController::class);

    Route::resource('jobcategories', JobCategoryController::class);
    Route::get('jobcategories/create/checkSlug', [JobCategoryController::class, 'checkSlug'])->name('jobcategory.checkSlug');

    Route::resource('jobseekers', JobSeekerController::class);
    
    Route::resource('companyindustries', CompanyIndustryController::class);
});

include('frontend.php');

app/Http/Controllers/Admin/AdminRoleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\AdminRoleRequest;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

class AdminRoleController extends Controller
{
    public function __construct()
    {
        $this->middleware('permission:role-list|role-create|role-edit|role-delete', ['only' => ['index', 'show']]);
        $this->middleware('permission:role-create', ['only' => ['create', 'store']]);
        $this->middleware('permission:role-edit', ['only' => ['edit', 'update']]);
        $this->middleware('permission:role-delete', ['only' => ['destroy']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $keyword = $request->query('keyword');

        // SEARCH USING KEYWORD
        $roles = $this->search($keyword);           

        return view('admin.adminrole.index', compact('roles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $permission = Permission::get();

        return view('admin.adminrole.create', compact('permission'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(AdminRoleRequest $request)
    {
        $role = Role::create([
            'name' => $request->input('name'),
        ]);

        $role->syncPermissions($request->input('permission'));

        return redirect()->route('admin.roles.index')->with('success', 'Role has been created Successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Role $role)
    {
        $permission = Permission::get();

        $rolePermissions = DB::table('role_has_permissions')->where('role_has_permissions.role_id', $role->id)->pluck('role_has_permissions.permission_id','role_has_permissions.permission_id')->all();

        // dd($rolePermissions);

        return view('admin.adminrole.edit', compact('role', 'permission', 'rolePermissions'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(AdminRoleRequest $request, Role $role)
    {
        $role->name = $request->input('name');
        $role->save();

        $role->syncPermissions($request->input('permission'));

        return redirect()->route('admin.roles.index')->with('status', 'Role Updated Successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Role $role)
    {
        $role->delete();

        return redirect()->route('admin.roles.index')->with('error', 'Role deleted Successfully!!');
    }

    // SEARCH FUNCTION FOR QUERYING
    public function search($keyword)
    {
        $roles = Role::whereHas('permissions', function($q) use($keyword) {
            $q->where('name', 'LIKE', "%$keyword%");
        })->orWhere('name', 'LIKE', "%$keyword%")
        ->get();

        return $roles;
    }
}

resources/views/admin/adminrole/create.blade.php
@extends('layouts.app')

@section('content')
<div id="layoutSidenav_content">
    <main>
        <div class="container-fluid px-4">
            <h1 class="mt-4">Admin Roles</h1>
            <ol class="breadcrumb mb-4">
                <li class="breadcrumb-item"><a href="{{ route('admin.home') }}">Dashboard</a></li>
                <li class="breadcrumb-item"><a href="{{ route('admin.roles.index') }}">Roles</a></li>
                <li class="breadcrumb-item active">Create</li>
            </ol>   
            <div class="d-flex justify-content-center">
                <div class="card mb-4 w-50">
                    <div class="card-header">
                        <i class="fas fa-table me-1"></i>
                        Create Admin Roles
                    </div>
                    <div class="card-body">
                        <form action="{{ route('admin.roles.store') }}" method="POST">
                            @csrf
                            <div class="form-floating mb-3">
                                <input class="form-control @error('name') is-invalid @enderror" id="inputname" type="text" placeholder="Name" name="name" value="{{ old('name') }}"/>
                                <label for="inputname">Name</label>
                                @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                            <div class=" mb-3 ms-2 row">
                                <label for="inputname" class="mb-2">Permission</label>
                                @foreach ($permission as $value)
                                    <div class="form-check">
                                        <input class="form-check-input @error('permission') is-invalid @enderror" name="permission[]" type="checkbox" value="{{ $value->id }}" id="flexCheckDefault" {{ in_array($value->id, old('permission', [])) ? 'checked' : '' }}>
                                        <label class="form-check-label" for="flexCheckDefault">
                                        {{ $value->name }}
                                        </label>
                                    </div>
                                <br/>
                                @endforeach
                                @error('permission')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                            <div class="mt-4 mb-0 d-flex justify-content-center">
                                <div class="d-grid w-25"><button type="submit" class="btn btn-primary btn-block">Create</button></div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </main>
</div>
@endsection

resources/views/admin/adminrole/edit.blade.php
@extends('layouts.app')

@section('content')
<div id="layoutSidenav_content">
    <main>
        <div class="container-fluid px-4">
            <h1 class="mt-4">Admin Roles</h1>
            <ol class="breadcrumb mb-4">
                <li class="breadcrumb-item"><a href="{{ route('admin.home') }}">Dashboard</a></li>
                <li class="breadcrumb-item"><a href="{{ route('admin.roles.index') }}">Roles</a></li>
                <li class="breadcrumb-item">{{ $role->name }}</li>
                <li class="breadcrumb-item active">Edit</li>
            </ol> 
            <div class="d-flex justify-content-center">
                <div class="card mb-4 w-50">
                    <div class="card-header">
                        <i class="fas fa-table me-1"></i>
                        Edit Admin Roles
                    </div>
                    <div class="card-body">
                        <form action="{{ route('admin.roles.update', $role->id) }}" method="POST">
                            @csrf
                            @method('PUT')
                            <div class="form-floating mb-3">
                                <input class="form-control @error('name') is-invalid @enderror" id="inputname" type="text" placeholder="Name" name="name" value="{{ old('name') ?? $role->name }}"/>
                                <label for="inputname">Name</label>
                                @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                            <div class=" mb-3 ms-2 row">
                                <label for="inputname" class="mb-2">Permission</label>
                                @foreach ($permission as $value)
                                    <div class="form-check">
                                        <input class="form-check-input @error('permission') is-invalid @enderror" name="permission[]" type="checkbox" value="{{ $value->id }}" id="flexCheckDefault" {{ in_array($value->id, $rolePermissions) ? 'checked' : '' }}>
                                        <label class="form-check-label" for="flexCheckDefault">
                                        {{ $value->name }}
                                        </label>
                                    </div>
                                <br/>
                                @endforeach
                                @error('permission')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                            <div class="mt-4 mb-0 d-flex justify-content-center">
                                <div class="d-grid w-25"><button type="submit" class="btn btn-primary btn-block">Update</button></div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </main>
</div>
@endsection

resources/views/admin/adminrole/index.blade.php
@extends('layouts.app')

@section('content')
<div id="layoutSidenav_content">
    <main>
        <div class="container-fluid px-4">
            <h1 class="mt-4">Admin Roles</h1>
            <ol class="breadcrumb mb-4">
                <li class="breadcrumb-item"><a href="{{ route('admin.home') }}">Dashboard</a></li>
                <li class="breadcrumb-item active">Roles</li>
            </ol>
            @include('frontend.layouts.alert')
            <div class="mb-3">
                <form action="" class="row g-3">
                    <div class="col-sm-3">
                        <input type="search" name="keyword" class="form-control" placeholder="Search" value="{{ request()->query('keyword') }}">
                    </div>
                    <div class="col-sm-2">
                        <button class="btn btn-primary me-1"><i class="fa fa-search me-1" aria-hidden="true"></i>Search</button>

                        <a href="{{ route('admin.roles.index') }}">
                            <button type="button" class="btn btn-danger"><i class="fa-solid fa-backward me-1"></i></i>Reset</button>
                        </a>
                    </div>
                </form>
            </div>            
            <div class="card mb-4">
                <div class="card-header">
                    <i class="fas fa-table me-1"></i>
                    Admin Roles
                    @can('role-create')
                    <a class="btn btn-success float-end" href ="{{ route('admin.roles.create') }}"><i class="fa-solid fa-plus"></i>
                        Add Role
                    </a>
                    @endcan
                </div>
                <div class="card-body">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th class="col-1">S.N.</th>
                                <th class="col-2">Name</th>
                                <th class="col-4">Permissions</th>
                                <th class="col-5">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($roles as $role)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $role->name }}</td>
                                <td>
                                    @foreach ($role->permissions as $permission)
                                    {{ $loop->iteration }}.
                                        {{ $permission->name }},<br>
                                    @endforeach
                                </td>
                                <td class="d-flex justify-content-start">
                                    @if ($role->name != 'SuperAdmin')
                                        @can('role-edit')
                                            <a class="btn btn-sm btn-warning me-1" href="{{ route('admin.roles.edit', $role->id) }}"><i class="fa-solid fa-pen-to-square me-1"></i>Edit</a>
                                        @endcan
                                        
                                        @can('role-delete')
                                            <form action="{{ route('admin.roles.destroy', $role->id) }}" method="POST" class="">
                                                @csrf
                                                @method('DELETE')
                                                <button type="submit" class="btn btn-sm btn-danger me-1"><i class="fa-solid fa-trash-can me-1"></i>Delete</button>
                                            </form>        
                                        @endcan
                                    @endif     
                                    <a class="me-1" href="{{ route('admin.users.index', ['role' => $role->id]) }}"><i class="fa-solid fa-user-group me-1"></i>{{ $role->users->count() }}</a>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </main>
</div>
@endsection