routes/frontend.php
<?php

use App\Http\Controllers\Frontend\Company\Auth\CompanyForgotPasswordController;
use App\Http\Controllers\Frontend\Company\Auth\CompanyLoginController;
use App\Http\Controllers\Frontend\Company\Auth\CompanyRegisterController;
use App\Http\Controllers\Frontend\Company\Auth\CompanyResetPasswordController;
use App\Http\Controllers\Frontend\Company\CompanyHomeController;
use App\Http\Controllers\Frontend\JobSeeker\Auth\JobSeekerForgotPasswordController;
use App\Http\Controllers\Frontend\JobSeeker\Auth\JobSeekerLoginController;
use App\Http\Controllers\Frontend\JobSeeker\Auth\JobSeekerRegisterController;
use App\Http\Controllers\Frontend\JobSeeker\Auth\JobSeekerResetPasswordController;
use App\Http\Controllers\Frontend\JobSeeker\JobSeekerEducationController;
use App\Http\Controllers\Frontend\JobSeeker\JobSeekerExperienceController;
use App\Http\Controllers\Frontend\JobSeeker\JobSeekerHomeController;
use App\Http\Controllers\Frontend\JobSeeker\JobSeekerProfileController;
use App\Http\Controllers\Frontend\JobSeeker\JobSeekerResumeController;
use Illuminate\Support\Facades\Route;

    Route::get('/', function () {
        return view('frontend.index');
    })->name('index');

    Route::prefix('jobseeker')->name('jobseeker.')->group(function() {
        Route::get('register', [JobSeekerRegisterController::class, 'viewRegister'])->name('register.view');
        Route::post('register', [JobSeekerRegisterController::class, 'register'])->name('register');
        
        Route::get('login', [JobSeekerLoginController::class, 'viewlogin'])->name('login.view');
        Route::post('login', [JobSeekerLoginController::class, 'login'])->name('login');

        Route::post('logout', [JobSeekerLoginController::class, 'logout'])->name('logout');

        Route::post('password/email', [JobSeekerForgotPasswordController::class, 'sendResetLinkEmail'])->name('password.email');
        Route::get('password/reset', [JobSeekerForgotPasswordController::class, 'showLinkRequestForm'])->name('password.request');

        Route::post('password/reset', [JobSeekerResetPasswordController::class, 'reset']);
        Route::get('password/reset/{token}', [JobSeekerResetPasswordController::class, 'showResetForm'])->name('password.reset');

        Route::middleware('auth:jobseeker')->group(function() {
            Route::get('home', [JobSeekerHomeController::class, 'index'])->name('home');

            Route::get('profile', [JobSeekerProfileController::class, 'index'])->name('profile');
            Route::put('profile/update', [JobSeekerProfileController::class, 'update'])->name('profile.update');
            Route::put('profile/picture/delete', [JobSeekerProfileController::class, 'destroyPhoto'])->name('profile.picture.delete');

            Route::get('education', [JobSeekerEducationController::class, 'index'])->name('education');

            Route::get('experience', [JobSeekerExperienceController::class, 'index'])->name('experience');

            Route::get('resume', [JobSeekerResumeController::class, 'index'])->name('resume');
        });
    });

    Route::prefix('company')->name('company.')->group(function() {
        Route::namespace('Auth')->group(function() {
            Route::get('register', [CompanyRegisterController::class, 'viewRegister'])->name('register.view');
            Route::post('register', [CompanyRegisterController::class, 'register'])->name('register');
    
            Route::get('login', [CompanyLoginController::class, 'viewlogin'])->name('login.view');
            Route::post('login', [CompanyLoginController::class, 'login'])->name('login');

            Route::post('logout', [CompanyLoginController::class, 'logout'])->name('logout');

            Route::get('password/reset', [CompanyForgotPasswordController::class, 'viewRequestForm'])->name('password.request');
            Route::post('password/email', [CompanyForgotPasswordController::class, 'sendResetLink'])->name('password.email');

            Route::get('password/reset/{token}', [CompanyResetPasswordController::class, 'viewResetForm'])->name('password.reset');
            Route::post('password/reset', [CompanyResetPasswordController::class, 'updatePassword'])->name('password.update');
        });
        
        Route::middleware('auth:company')->group(function() {
            Route::get('home', [CompanyHomeController::class, 'index'])->name('home');
        });
    });

?>

routes/web.php
<?php

use App\Http\Controllers\Admin\AdminRoleController;
use App\Http\Controllers\Admin\AdminUserController;
use App\Http\Controllers\Admin\CompanyIndustryController;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\JobCategoryController;
use App\Http\Controllers\Admin\JobSeekerController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['register' => false]);

Route::middleware('auth')->prefix('admin')->name('admin.')->group(function() {
    Route::get('/home', [HomeController::class, 'index'])->name('home');
    
    Route::resource('users', AdminUserController::class);
    Route::get('users/{user}/reset-password', [AdminUserController::class, 'showResetForm'])->name('users.password.show');
    Route::put('users/{user}/resets', [AdminUserController::class, 'resetPassword'])->name('users.password.reset');

    Route::resource('roles', AdminRoleController::class);

    Route::resource('jobcategories', JobCategoryController::class);
    Route::get('jobcategories/create/checkSlug', [JobCategoryController::class, 'checkSlug'])->name('jobcategory.checkSlug');

    Route::resource('jobseekers', JobSeekerController::class);
    
    Route::resource('companyindustries', CompanyIndustryController::class);
});

include('frontend.php');

app/Models/JobCategory.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class JobCategory extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'slug',
        'status',
    ];
}

app/Http/Controllers/Admin/JobCategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\JobCategoryRequest;
use App\Models\JobCategory;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class JobCategoryController extends Controller
{
    public function __construct()
    {
        $this->middleware('permission:jobcategory-list|jobcategory-create|jobcategory-edit|jobcategory-delete', ['only' => ['index', 'show']]);
        $this->middleware('permission:jobcategory-create', ['only' => ['create', 'store']]);
        $this->middleware('permission:jobcategory-edit', ['only' => ['edit', 'update']]);
        $this->middleware('permission:jobcategory-delete', ['only' => ['destroy']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $jobcategories = $this->search($request);

        return view('admin.jobcategory.index', compact('jobcategories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.jobcategory.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(JobCategoryRequest $request)
    {
        JobCategory::create($request->validated());

        return redirect()->route('admin.jobcategories.index')->with('success', 'Job Category added!!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(JobCategory $jobcategory)
    {
        return view('admin.jobcategory.edit', compact('jobcategory'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(JobCategoryRequest $request, JobCategory $jobcategory)
    {
        $jobcategory->update($request->validated());

        return redirect()->route('admin.jobcategories.index')->with('status', 'Job Category Updated!!!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(JobCategory $jobcategory)
    {
        $jobcategory->delete();

        return redirect()->route('admin.jobcategories.index')->with('error', 'Job Category Deleted!!!');
    }

    public function checkSlug(Request $request)
    {
        // MAKE SLUG FROM NAME USING JQUERY

        $slug = Str::slug($request->name);

        return response()->json(['slug' => $slug]);
    }

    public function search($request)
    {
        $keyword = $request->query('keyword');
        $queryStatus = $request->query('status');

        // SEARCH USING KEYWORD AND STATUS

        if ($queryStatus === NULL || ($queryStatus != 1 && $queryStatus != 0)) {
            $queryStatus = 'all';
        }

        if (empty($keyword) && ($queryStatus == "all")) {
            $jobcategories = JobCategory::get();
        }
        elseif ($queryStatus == 'all') {
            $jobcategories = JobCategory::where('name', 'LIKE', "%$keyword%")
                ->orWhere('slug', 'LIKE', "%$keyword%")
                ->get();
        }
        elseif (empty($keyword)) {
            $jobcategories = JobCategory::where('status', '=', $queryStatus)->get();
        }
        elseif (!empty($keyword) && ($queryStatus !== "all")) {
            $jobcategories = JobCategory::where([
                    ['status', '=', $queryStatus],
                    ['name', 'LIKE', "%$keyword%"]
                ])->orWhere([
                    ['status', '=', $queryStatus],
                    ['slug', 'LIKE', "%$keyword%"]
                ])->get();
        }

        return $jobcategories;
    }
}

resources/views/admin/jobcategory/create.blade.php
@extends('layouts.app')

@section('content')
<div id="layoutSidenav_content">
    <main>
        <div class="container-fluid px-4">
            <h1 class="mt-4">Job Categories</h1>
            <ol class="breadcrumb mb-4">
                <li class="breadcrumb-item"><a href="{{ route('admin.home') }}">Dashboard</a></li>
                <li class="breadcrumb-item"><a href="{{ route('admin.jobcategories.index') }}">Job Categories</a></li>
                <li class="breadcrumb-item active">Create</li>
            </ol> 
            <div class="d-flex justify-content-center">
                <div class="card mb-4 w-50">
                    <div class="card-header">
                        <i class="fas fa-table me-1"></i>
                        Create Job Categories
                    </div>
                    <div class="card-body">
                        <form action="{{ route('admin.jobcategories.store') }}" method="POST">
                            @csrf
                            <div class="form-floating mb-3">
                                <input class="form-control @error('name') is-invalid @enderror" id="name" type="text" placeholder="Name" name="name" value="{{ old('name') }}"/>
                                <label for="name">Name</label>
                                @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                            <div class="form-floating mb-3">
                                <input class="form-control @error('slug') is-invalid @enderror" id="slug" type="text" placeholder="Slug" name="slug" value="{{ old('slug') }}" />
                                <label for="slug">Slug</label>
                                @error('slug')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                            <div class="form-floating mb-3 ms-2 row">
                                <div class="form-check col-2">
                                    <input class="form-check-input @error('status') is-invalid @enderror" type="radio" name="status" id="flexRadioDefault1" value="1" {{ (old('status') == "1") ? 'checked' : '' }}>
                                    <label class="form-check-label" for="flexRadioDefault1">
                                    Active
                                    </label>
                                </div>
                                <div class="form-check col-2">
                                    <input class="form-check-input @error('status') is-invalid @enderror" type="radio" name="status" id="flexRadioDefault2" value="0" {{ (old('status') == "0") ? 'checked' : '' }}>
                                    <label class="form-check-label" for="flexRadioDefault2">
                                    Inactive
                                    </label>
                                </div>
                                @error('status')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                            <div class="mt-4 mb-0 d-flex justify-content-center">
                                <div class="d-grid w-25"><button type="submit" class="btn btn-primary btn-block">Create</button></div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </main>
</div>
<script>
    $('#name').change(function(e) {
      $.get('{{ route('admin.jobcategory.checkSlug') }}', 
        { 'name': $(this).val() }, 
        function( data ) {
          $('#slug').val(data.slug);
        }
      );
    });
</script>
@endsection

resources/views/admin/jobcategory/edit.blade.php
@extends('layouts.app')

@section('content')
<div id="layoutSidenav_content">
    <main>
        <div class="container-fluid px-4">
            <h1 class="mt-4">Job Categories</h1>
            <ol class="breadcrumb mb-4">
                <li class="breadcrumb-item"><a href="{{ route('admin.home') }}">Dashboard</a></li>
                <li class="breadcrumb-item"><a href="{{ route('admin.jobcategories.index') }}">Job Categories</a></li>
                <li class="breadcrumb-item active">Create</li>
            </ol>
            <div class="d-flex justify-content-center"> 
                <div class="card mb-4 w-50">
                    <div class="card-header">
                        <i class="fas fa-table me-1"></i>
                        Create Job Categories
                    </div>
                    <div class="card-body">
                        <form action="{{ route('admin.jobcategories.update', $jobcategory) }}" method="POST">
                            @csrf
                            @method('PUT')
                            <div class="form-floating mb-3">
                                <input class="form-control @error('name') is-invalid @enderror" id="inputname" type="text" placeholder="Name" name="name" value="{{ old('name') ?? $jobcategory->name }}"/>
                                <label for="inputname">Name</label>
                                @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                            <div class="form-floating mb-3">
                                <input class="form-control" id="inputslug" type="slug" placeholder="slug" name="slug" value="{{ old('slug') ?? $jobcategory->slug }}" />
                                <label for="inputslug">Slug</label>
                                @error('slug')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                            <div class="form-floating mb-3 ms-2 row">
                                <div class="form-check col-2">
                                    <input class="form-check-input @error('status') is-invalid @enderror" type="radio" name="status" id="flexRadioDefault1" value="1" {{ (old('status') || $jobcategory->status) == 1 ? 'checked' : '' }}>
                                    <label class="form-check-label" for="flexRadioDefault1">
                                    Active
                                    </label>
                                </div>
                                <div class="form-check col-2">
                                    <input class="form-check-input @error('status') is-invalid @enderror" type="radio" name="status" id="flexRadioDefault2" value="0" {{ (old('status') || $jobcategory->status) == 0 ? 'checked' : '' }}>
                                    <label class="form-check-label" for="flexRadioDefault2">
                                    Inactive
                                    </label>
                                </div>
                                @error('status')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                            <div class="mt-4 mb-0 d-flex justify-content-center">
                                <div class="d-grid w-25"><button type="submit" class="btn btn-primary btn-block">Update</button></div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </main>
</div>
@endsection

resources/views/admin/jobcategory/index.blade.php
@extends('layouts.app')

@section('content')
<div id="layoutSidenav_content">
    <main>
        <div class="container-fluid px-4">
            <h1 class="mt-4">Job Categories</h1>
            <ol class="breadcrumb mb-4">
                <li class="breadcrumb-item"><a href="{{ route('admin.home') }}">Dashboard</a></li>
                <li class="breadcrumb-item active">Job Categories</li>
            </ol>  
            @include('frontend.layouts.alert')
            <div class="mb-3">
                <form action="" class="row g-3">
                    <div class="col-sm-3">
                        <input type="search" name="keyword" class="form-control" placeholder="Search" value="{{ request()->query('keyword') }}">
                    </div>
                    <div class="col-sm-2">
                        <select type="search" name="status" class="form-control" placeholder="Search" aria-label="Search">
                            <option value="all">All</option>
                            <option value=1 {{ request()->query('status') == '1' ? 'selected' : '' }}>Active</option>
                            <option value=0 {{ request()->query('status') == '0' ? 'selected' : '' }}>Inactive</option>
                        </select>
                    </div>
                    <div class="col-sm-2">
                        <button class="btn btn-primary me-1"><i class="fa fa-search me-1" aria-hidden="true"></i>Search</button>

                        <a href="{{ route('admin.jobcategories.index') }}">
                            <button type="button" class="btn btn-danger"><i class="fa-solid fa-backward me-1"></i></i>Reset</button>
                        </a>
                    </div>
                </form>
            </div>      
            <div class="card mb-4">
                <div class="card-header">
                    <i class="fas fa-table me-1"></i>
                    Job Categories
                    @can('jobcategory-create')
                    <a class="btn btn-success float-end" href ="{{ route('admin.jobcategories.create') }}"><i class="fa-solid fa-plus"></i>
                        Create
                    </a>
                    @endcan
                </div>
                <div class="card-body">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th class="col-1">S.N</th>
                                <th class="col-3">Name</th>
                                <th class="col-3">Slug</th>
                                <th class="col-2">Status</th>
                                <th class="col-3">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($jobcategories as $jobcategory)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $jobcategory->name }}</td>
                                <td>{{ $jobcategory->slug }}</td>
                                <td>
                                    <label class="badge {{ ($jobcategory->status) == 1 ? 'bg-success' : 'bg-danger' }}">
                                        {{ ($jobcategory->status) == 1 ? 'Active' : 'Inactive' }}
                                    </label>
                                </td>
                                <td class="d-flex justify-content-start">
                                    @can('jobcategory-edit')
                                        <a class="btn btn-sm btn-warning me-1" href="{{ route('admin.jobcategories.edit', $jobcategory) }}"><i class="fa-solid fa-pen-to-square me-1"></i>Edit</a>
                                    @endcan
                                    
                                    @can('jobcategory-delete')
                                        <form action="{{ route('admin.jobcategories.destroy', $jobcategory) }}" method="POST" class="">
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-sm btn-danger me-1"><i class="fa-solid fa-trash-can me-1"></i>Delete</button>
                                        </form>
                                    @endcan
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </main>
</div>
@endsection